version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
        - "5432:5432"
    volumes:
        - ./data/postgres:/var/lib/postgresql/data    
    env_file:
        - .env
    networks:
        - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin_container
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - ./data/pgadmin:/var/lib/pgadmin
    env_file:
    - .env
    networks:
    - postgres
 

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net


networks:
  postgres:
    driver: bridge
  rabbitmq_go_net:
    driver: bridge
  